"""
Data models for Delphi-AHP pipeline.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class Expert:
    """Expert definition."""
    id: str
    name: str
    role: str
    org_type: str
    region: str
    expertise: str
    language: str
    scoring_bias: str
    enabled: bool = True

    # LLM settings
    provider: str = ""
    provider_name: str = ""
    model: str = ""
    api_key: str = ""
    base_url: str = ""
    adapter: str = ""

    # Detailed professional profile (generated by LLM, used for prompts)
    pro: str = ""

    # Extended expert profile fields (reference: 17-experts agents.json structure)
    capability_base: str = ""   # Capability background description
    behavior_style: str = ""    # Behavior style description
    interview_focus: str = ""  # Interview focus direction
    profile: str = ""           # Detailed persona description (2-3 paragraphs)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "role": self.role,
            "org_type": self.org_type,
            "region": self.region,
            "expertise": self.expertise,
            "language": self.language,
            "scoring_bias": self.scoring_bias,
            "enabled": self.enabled,
            "provider": self.provider,
            "provider_name": self.provider_name,
            "model": self.model,
            "api_key": self.api_key,
            "base_url": self.base_url,
            "adapter": self.adapter,
            "pro": self.pro,
            "capability_base": self.capability_base,
            "behavior_style": self.behavior_style,
            "interview_focus": self.interview_focus,
            "profile": self.profile,
        }

    def get(self, key: str, default=None):
        """dict-compatible get method for dict/object interoperability."""
        if hasattr(self, key):
            return getattr(self, key)
        return default


@dataclass
class Provider:
    """LLM Provider configuration."""
    key: str
    name: str
    adapter: str
    base_url: str
    api_key: str
    default_model: str
    models: list
    model_capabilities: dict = None  # Dict[str, int] mapping model name -> max_tokens

    def __post_init__(self):
        if self.model_capabilities is None:
            self.model_capabilities = {}

    def to_dict(self) -> dict:
        return {
            "key": self.key,
            "name": self.name,
            "adapter": self.adapter,
            "base_url": self.base_url,
            "api_key": self.api_key,
            "default_model": self.default_model,
            "models": self.models,
            "model_capabilities": self.model_capabilities,
        }


@dataclass
class ScoringDimension:
    """Scoring dimension for Delphi round 2."""
    name: str
    weight: float


@dataclass
class RoundsConfig:
    """Delphi rounds configuration."""
    round_1_turns: int = 5
    round_2_dimensions: list = field(default_factory=list)
    convergence_threshold: float = 0.5
    max_rounds: int = 3
    # Interview dynamics settings
    max_turns_per_expert: int = 20  # Maximum conversation turns per expert
    min_follow_ups_per_topic: int = 3  # Minimum follow-ups before switching topics
    max_follow_ups_per_topic: int = 8  # Maximum follow-ups per topic

    def to_dict(self) -> dict:
        return {
            "round_1": {
                "turns": self.round_1_turns,
            },
            "round_2": {
                "scoring_dimensions": [
                    {"name": d.name, "weight": d.weight}
                    for d in self.round_2_dimensions
                ],
            },
            "convergence_threshold": self.convergence_threshold,
            "max_rounds": self.max_rounds,
            "interview_dynamics": {
                "max_turns_per_expert": self.max_turns_per_expert,
                "min_follow_ups_per_topic": self.min_follow_ups_per_topic,
                "max_follow_ups_per_topic": self.max_follow_ups_per_topic,
            },
        }


@dataclass
class Project:
    """Research project definition."""
    title: str
    framework: str
    background: str
    purpose: str
    boundaries: str
    research_questions: list = field(default_factory=list)
    delphi_lang: str = "zh"  # Language for Delphi output: "zh" or "en"

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "framework": self.framework,
            "background": self.background,
            "purpose": self.purpose,
            "boundaries": self.boundaries,
            "research_questions": self.research_questions,
            "delphi_lang": self.delphi_lang,
        }


@dataclass
class Factor:
    """Identified factor from Delphi."""
    id: str
    name: str
    description: str = ""
    source: str = ""


@dataclass
class Transcript:
    """Expert transcript from Delphi round 1."""
    expert_id: str
    expert: dict
    answer: str
    factors: list


@dataclass
class Score:
    """Expert score for a factor."""
    expert_id: str
    factor_id: str
    factor_name: str
    score: float
    reasoning: str = ""


@dataclass
class AHPResult:
    """AHP calculation result."""
    weights: dict
    factor_details: list
    consistency_ratio: float
    consistency_passed: bool
    matrix: list
    lambda_max: float


@dataclass
class RunState:
    """Pipeline run state."""
    run_id: str
    project: Project
    providers: dict  # {key: Provider}
    experts: list    # [Expert]
    rounds: RoundsConfig
    factors: list = field(default_factory=list)
    status: str = "created"

    def to_dict(self) -> dict:
        return {
            "run_id": self.run_id,
            "project": self.project.to_dict(),
            "providers": {k: v.to_dict() for k, v in self.providers.items()},
            "experts": [e.to_dict() for e in self.experts],
            "rounds": self.rounds.to_dict(),
            "factors": self.factors,
            "status": self.status,
        }
